blank_issues_enabled: false
contact_links:
  - name: Contacto institucional
    url: mailto:mineriayenergia@produccionsalta.gob.ar
    about: Para consultas institucionales que no correspondan a un reporte de error o solicitud de mejora.
